In [1]:
print('\nEnabling interactive shell outputs ...')
print('   Use command pass; to disable cell text outputs')
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import warnings
warnings.filterwarnings('ignore') 
warnings.simplefilter(action="ignore",category=UserWarning)
warnings.simplefilter(action="ignore",category=FutureWarning)

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statsmodels.api as sm



%matplotlib inline
%config InlineBackend.figure_formats = {'png', 'retina'}

Enabling interactive shell outputs ...
   Use command pass; to disable cell text outputs

In [22]:
data = np.array([[0.80, 125, 275, 550],
                        [1.20, 125, 275, 669],
                        [0.80, 200, 275, 633],
                        [1.20, 200, 275, 642],
                        [0.80, 125, 325, 1037],
                        [1.20, 125, 325, 749],
                        [0.80, 200, 325, 1075],
                        [1.20, 200, 325, 729],
                        [0.80, 125, 275, 604],
                        [1.20, 125, 275, 650],
                        [0.80, 200, 275, 601],
                        [1.20, 200, 275, 635],
                        [0.80, 125, 325, 1052],
                        [1.20, 125, 325, 868],
                        [0.80, 200, 325, 1063],
                        [1.20, 200, 325, 860]])
plasma_data_natural = pd.DataFrame(data, columns=['Gap','C2F6flow','Power','Etch_rate'])
plasma_data_natural

    Gap  C2F6flow  Power  Etch_rate
0   0.8     125.0  275.0      550.0
1   1.2     125.0  275.0      669.0
2   0.8     200.0  275.0      633.0
3   1.2     200.0  275.0      642.0
4   0.8     125.0  325.0     1037.0
5   1.2     125.0  325.0      749.0
6   0.8     200.0  325.0     1075.0
7   1.2     200.0  325.0      729.0
8   0.8     125.0  275.0      604.0
9   1.2     125.0  275.0      650.0
10  0.8     200.0  275.0      601.0
11  1.2     200.0  275.0      635.0
12  0.8     125.0  325.0     1052.0
13  1.2     125.0  325.0      868.0
14  0.8     200.0  325.0     1063.0
15  1.2     200.0  325.0      860.0

In [24]:
from statsmodels.formula.api import ols

formula = 'Etch_rate ~ Gap*C2F6flow*Power'
#formula = 'Etch_rate ~ Gap*C2F6flow*Power - 1'

plasma_lm = ols(formula, data = plasma_data_natural).fit()
plasma_lm.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                       Results: Ordinary least squares
=============================================================================
Model:                  OLS                  Adj. R-squared:         0.936
Dependent Variable:     Etch_rate            AIC:                    173.8329
Date:                   2021-12-04 16:25     BIC:                    180.0136
No. Observations:       16                   Log-Likelihood:         -78.916
Df Model:               7                    F-statistic:            32.56
Df Residuals:           8                    Prob (F-statistic):     2.90e-05
R-squared:              0.966                Scale:                  2252.6
-----------------------------------------------------------------------------
                     Coef.     Std.Err.    t    P>|t|     [0.025     0.975]
-----------------------------------------------------------------------------
Intercept          -6487.3333 3239.9466 -2.0023 0.0802 -13958.6636   983.9970
Gap                 5355.4167 3177.0290  1.6857 0.1303  -1970.8255 12681.6588
C2F6flow               6.5967   19.4275  0.3396 0.7429    -38.2033    51.3967
Gap:C2F6flow          -6.1583   19.0503 -0.3233 0.7548    -50.0883    37.7717
Power                 24.1067   10.7625  2.2399 0.0554     -0.7117    48.9251
Gap:Power            -17.8000   10.5535 -1.6866 0.1302    -42.1365     6.5365
C2F6flow:Power        -0.0161    0.0645 -0.2500 0.8089     -0.1650     0.1327
Gap:C2F6flow:Power     0.0150    0.0633  0.2370 0.8186     -0.1309     0.1609
-----------------------------------------------------------------------------
Omnibus:                 0.627           Durbin-Watson:              2.002
Prob(Omnibus):           0.731           Jarque-Bera (JB):           0.008
Skew:                    0.000           Prob(JB):                   0.996
Kurtosis:                3.109           Condition No.:              27158184
=============================================================================
* The condition number is large (3e+07). This might indicate
strong multicollinearity or other numerical problems.
"""

In [23]:
data = np.array([[-1, -1, -1, 550],
                        [+1, -1, -1, 669],
                        [-1, +1, -1, 633],
                        [+1, +1, -1, 642],
                        [-1, -1, +1, 1037],
                        [+1, -1, +1, 749],
                        [-1, +1, +1, 1075],
                        [+1, +1, +1, 729],
                        [-1, -1, -1, 604],
                        [+1, -1, -1, 650],
                        [-1, +1, -1, 601],
                        [+1, +1, -1, 635],
                        [-1, -1, +1, 1052],
                        [+1, -1, +1, 868],
                        [-1, +1, +1, 1063],
                        [+1, +1, +1, 860]])
plasma_data_coded = pd.DataFrame(data, columns=['Gap','C2F6flow','Power','Etch_rate'])
plasma_data_coded

    Gap  C2F6flow  Power  Etch_rate
0    -1        -1     -1        550
1     1        -1     -1        669
2    -1         1     -1        633
3     1         1     -1        642
4    -1        -1      1       1037
5     1        -1      1        749
6    -1         1      1       1075
7     1         1      1        729
8    -1        -1     -1        604
9     1        -1     -1        650
10   -1         1     -1        601
11    1         1     -1        635
12   -1        -1      1       1052
13    1        -1      1        868
14   -1         1      1       1063
15    1         1      1        860

In [25]:
from statsmodels.formula.api import ols

formula = 'Etch_rate ~ Gap*C2F6flow*Power'
#formula = 'Etch_rate ~ Gap*C2F6flow*Power - 1'

plasma_lm = ols(formula, data = plasma_data_coded).fit()
plasma_lm.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                   Results: Ordinary least squares
======================================================================
Model:                 OLS               Adj. R-squared:      0.936
Dependent Variable:    Etch_rate         AIC:                 173.8329
Date:                  2021-12-04 16:25  BIC:                 180.0136
No. Observations:      16                Log-Likelihood:      -78.916
Df Model:              7                 F-statistic:         32.56
Df Residuals:          8                 Prob (F-statistic):  2.90e-05
R-squared:             0.966             Scale:               2252.6
----------------------------------------------------------------------
                    Coef.   Std.Err.    t    P>|t|    [0.025   0.975]
----------------------------------------------------------------------
Intercept          776.0625  11.8653 65.4061 0.0000  748.7011 803.4239
Gap                -50.8125  11.8653 -4.2824 0.0027  -78.1739 -23.4511
C2F6flow             3.6875  11.8653  0.3108 0.7639  -23.6739  31.0489
Gap:C2F6flow       -12.4375  11.8653 -1.0482 0.3252  -39.7989  14.9239
Power              153.0625  11.8653 12.9000 0.0000  125.7011 180.4239
Gap:Power          -76.8125  11.8653 -6.4737 0.0002 -104.1739 -49.4511
C2F6flow:Power      -1.0625  11.8653 -0.0895 0.9308  -28.4239  26.2989
Gap:C2F6flow:Power   2.8125  11.8653  0.2370 0.8186  -24.5489  30.1739
----------------------------------------------------------------------
Omnibus:                 0.627         Durbin-Watson:            2.002
Prob(Omnibus):           0.731         Jarque-Bera (JB):         0.008
Skew:                    0.000         Prob(JB):                 0.996
Kurtosis:                3.109         Condition No.:            1
======================================================================

"""

In [6]:
Xmain=np.array([[+1,-1,-1,-1],
                [+1,+1,-1,-1],
                [+1,-1,+1,-1],
                [+1,+1,+1,-1],
                [+1,-1,-1,+1],
                [+1,+1,-1,+1],
                [+1,-1,+1,+1],
                [+1,+1,+1,+1]])

In [7]:
factorial_eff = pd.DataFrame(Xmain, columns=['Intercept','A','B','C'])

In [8]:
# Add interaction effects
factorial_eff['AB'] = factorial_eff['A']*factorial_eff['B']
factorial_eff['AC'] = factorial_eff['A']*factorial_eff['C']
factorial_eff['BC'] = factorial_eff['B']*factorial_eff['C']
factorial_eff['ABC'] = factorial_eff['A']*factorial_eff['B']*factorial_eff['C']
factorial_eff

   Intercept  A  B  C  AB  AC  BC  ABC
0          1 -1 -1 -1   1   1   1   -1
1          1  1 -1 -1  -1  -1   1    1
2          1 -1  1 -1  -1   1  -1    1
3          1  1  1 -1   1  -1  -1   -1
4          1 -1 -1  1   1  -1  -1    1
5          1  1 -1  1  -1   1  -1   -1
6          1 -1  1  1  -1  -1   1   -1
7          1  1  1  1   1   1   1    1

In [9]:
# Observations from two replicates
y = np.array([[550,604],
             [669,650],
             [633,601],
             [642,635],
             [1037,1052],
             [749,868],
             [1075,1063],
             [729,860]])

In [10]:
# Get a vector of total response
total_y = np.c_[y.sum(axis=1)]
total_y

array([[1154],
       [1319],
       [1234],
       [1277],
       [2089],
       [1617],
       [2138],
       [1589]])

In [11]:
k, n = np.log2(len(factorial_eff)), y.shape[1]

contrast_eff = factorial_eff.iloc[:,1:].mul(total_y).sum()
print('Contrast effects\n', contrast_eff.to_string(), sep='')

effects = (contrast_eff)/((2**(k-1))*n)
print('\nEffect estimates\n', effects.to_string(), sep='')

ss_eff = (contrast_eff**2)/((2**k)*n)
print('\nSS effects\n', ss_eff.to_string(), sep='')

Contrast effects
A      -813
B        59
C      2449
AB     -199
AC    -1229
BC      -17
ABC      45

Effect estimates
A     -101.625
B        7.375
C      306.125
AB     -24.875
AC    -153.625
BC      -2.125
ABC      5.625

SS effects
A       41310.5625
B         217.5625
C      374850.0625
AB       2475.0625
AC      94402.5625
BC         18.0625
ABC       126.5625

In [12]:
SST = (sum(sum(y**2)) - sum(total_y)**2/y.size)[0]
SSE = SST - sum(ss_eff)
MSE = SSE/(y.size - len(ss_eff) - 1)
print("SSE = {:.2f}, MSE = {:.2f}".format(SSE, MSE))

SSE = 18020.50, MSE = 2252.56

In [13]:
Fa = stats.f.sf(ss_eff['A']/MSE, 1, 8)
Fb = stats.f.sf(ss_eff['B']/MSE, 1, 8)
Fc = stats.f.sf(ss_eff['C']/MSE, 1, 8)
Fab = stats.f.sf(ss_eff['AB']/MSE, 1, 8)
Fac = stats.f.sf(ss_eff['AC']/MSE, 1, 8)
Fbc = stats.f.sf(ss_eff['BC']/MSE, 1, 8)
Fabc = stats.f.sf(ss_eff['ABC']/MSE, 1, 8)

In [14]:
print("p-value of Fa is", Fa)
print("p-value of Fb is", Fb)
print("p-value of Fc is", Fc)
print("p-value of Fab is", Fab)
print("p-value of Fac is", Fac)
print("p-value of Fbc is", Fbc)
print("p-value of Fabc is", Fabc)

p-value of Fa is 0.002678610470970536
p-value of Fb is 0.7639107082242301
p-value of Fc is 1.233261999311417e-06
p-value of Fab is 0.3251678561221075
p-value of Fac is 0.00019339576675897084
p-value of Fbc is 0.9308485642080134
p-value of Fabc is 0.8185860578539553

In [15]:
total_avg = sum(total_y)/16 # N = 16 (2*8)
total_avg

array([776.0625])

In [16]:
half_A = effects['A']/2
half_B = effects['B']/2
half_C = effects['C']/2
half_AB = effects['AB']/2
half_AC = effects['AC']/2
half_BC = effects['BC']/2
half_ABC = effects['ABC']/2

half_A, half_B, half_C, half_AB, half_AC, half_BC, half_ABC

(-50.8125, 3.6875, 153.0625, -12.4375, -76.8125, -1.0625, 2.8125)

regression model
y = 776.0625 - (50.8125)x1 + (3.6875)x2 + (153.0625)x3 - (12.4375)x1x2 - (76.8125)x1x3 - (1.0625)x2x3 + (2.8125)x1x2x3

In [17]:
import pandas as pd
import numpy as np

Xmain=np.array([[+1,-1,-1,-1],
                [+1,+1,-1,-1],
                [+1,-1,-1,+1],
                [+1,-1,+1,-1],
                [+1,+1,+1,-1],
                [+1,-1,+1,+1],
                [+1,+1,-1,+1],
                [+1,+1,+1,+1]])

factorial_eff = pd.DataFrame(Xmain, columns=['Intercept','A','B','C'])

factorial_eff['E=AC'] = factorial_eff['A']*factorial_eff['C']
factorial_eff['D = BE'] = factorial_eff['B']*factorial_eff['E=AC']
factorial_eff['E = AC'] = factorial_eff['E=AC']
del factorial_eff['E=AC']
factorial_eff['AB'] = factorial_eff['A']*factorial_eff['B']
factorial_eff['AD'] = factorial_eff['A']*factorial_eff['D = BE']
factorial_eff['treatment_combi'] = ['e','ad','cd','bde','ab','bc','ace','abcde']
factorial_eff['y'] = [23.2, 16.9, 23.8, 16.8, 15.5, 16.2, 23.4, 18.1]

factorial_eff

   Intercept  A  B  C  D = BE  E = AC  AB  AD treatment_combi     y
0          1 -1 -1 -1      -1       1   1   1               e  23.2
1          1  1 -1 -1       1      -1  -1   1              ad  16.9
2          1 -1 -1  1       1      -1   1  -1              cd  23.8
3          1 -1  1 -1       1       1  -1  -1             bde  16.8
4          1  1  1 -1      -1      -1   1  -1              ab  15.5
5          1 -1  1  1      -1      -1  -1   1              bc  16.2
6          1  1 -1  1      -1       1  -1  -1             ace  23.4
7          1  1  1  1       1       1   1   1           abcde  18.1

In [18]:
y = factorial_eff['y']
total_y = np.c_[factorial_eff['y']]
total_y
del factorial_eff['y']
del factorial_eff['treatment_combi']

array([[23.2],
       [16.9],
       [23.8],
       [16.8],
       [15.5],
       [16.2],
       [23.4],
       [18.1]])

In [19]:
k, n = 5, 1

contrast_eff = factorial_eff.iloc[:,1:].mul(total_y).sum()
print('Contrast effects\n', contrast_eff.to_string(), sep='')

effects = (contrast_eff)/(((2**(k-2))*n)/2)
print('\nEffect estimates\n', effects.to_string(), sep='')

Contrast effects
A         -6.1
B        -20.7
C          9.1
D = BE    -2.7
E = AC     9.1
AB         7.3
AD        -5.1

Effect estimates
A        -1.525
B        -5.175
C         2.275
D = BE   -0.675
E = AC    2.275
AB        1.825
AD       -1.275

In [20]:
alias_structure = ['[A] = A + CE', '[B] = B + DE', '[C] = C + AE', '[D] = D + BE',
                   '[E] = E + AC + BD', '[AB] = AB + CD', '[AD] = AD + BC']
effect = np.array([-1.525, -5.175, 2.275, -0.675, 2.275, 1.825, -1.275])

data = {'Alias Structure':alias_structure,'Estimates Effect':effect}

eff_estimate = pd.DataFrame(data)
eff_estimate

     Alias Structure  Estimates Effect
0       [A] = A + CE            -1.525
1       [B] = B + DE            -5.175
2       [C] = C + AE             2.275
3       [D] = D + BE            -0.675
4  [E] = E + AC + BD             2.275
5     [AB] = AB + CD             1.825
6     [AD] = AD + BC            -1.275